import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Himalaya Facewash',
    cookTime: '10-20',
    price: 147,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['BeautyCare'],
  },
  {
    id:'2',
    name: 'Biomagic Hair Color Cream',
    price: 74.85,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['BeautyCare'],
  },
  {
    id:'3',
    name: 'Apricot Scrub',
    price: 33.50,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['PersonalCare'],
  },
  {
    id:'4',
    name: 'Panadol Blue',
    price: 5.00,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['MedicineAndTreatment'],
  },
  {
    id:'5',
    name: 'Paradox Omega 3',
    price: 93.00,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['Vitamins'],
  },
  {
    id:'6',
    name: 'King.C.Gillette, Beard Trimmer',
    price: 151.86,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['PersonalCare'],
  },
  {
    id:'7',
    name: 'Metanium Nappy Rash Ointment, 30g ',
    price: 1832,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['MumAndBaby'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 6 },
  { name: 'BeautyCare', count: 2 },
  { name: 'PersonalCare', count: 2 },
  { name: 'MedicineAndTreatment', count: 1 },
  { name: 'Vitamins', count: 1 },
  { name: 'MumAndBaby', count: 0 }
]
